Update test-actions.yml

diff --git a/.github/workflows/test-actions.yml b/.github/workflows/test-actions.yml
--- a/.github/workflows/test-actions.yml
+++ b/.github/workflows/test-actions.yml
@@ -17,8 +17,18 @@ jobs:
         run: |
           if [ -d "indoxDocs/classic/" ]; then
             echo "✅ Directory exists!"
-            ls -la indoxDocs/classic/
           else
             echo "❌ Directory missing!"
+            exit 1
+          fi
+
+      - name: ✅ Install Dependencies
+        run: |
+          cd indoxDocs/classic
+          echo "📦 Running npm install..."
+          if npm install; then
+            echo "✅ npm install completed successfully."
+          else
+            echo "❌ npm install failed!"
             exit 1
           fi
